---
services: docker

env:
  # Defaults.
  - distro: centos7

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/sylus/e5d6eb8852d649ae78477b2daf86e707/raw
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

notifications:
  slack:
    secure: G/9+y+cy8q+41EotX5aXffQwk/p6k1f1f5LoXYeDS4IJUC/Ikyw3WMLGCucPjheJGZls/nw0mRen0u3jvoFjOCsnY/j10wXc9y2BG84rsI1EPpgY4keT/P46ZsLg0+giLeAXaN7mg2nSqLip0XvEn2JjF/h8IHqz7TySLZ9IiohEm5Ra+nJOObQWvky5vCqrYHYxtbybF3e3rKgAP8EhE28i+GSrGzfF6CgRSZG0gj4oHdQAGv6LkBCMJab6aboNTdQyYI3zcmJzCX/PcO6Fp1PE3I8PvRoQbCubjMdamE/ASjW9No9CScSFHzvrpSu+vgGXjQanLOx50x8y6xJPZJlKt6YigmPgZiAzWFfOCgQLZ8izz4wrVm0v80UusOubcYIlVwk7S/0f4DtyToL4qjDGLfsPCZV8DZHE8jIcvRC3COVxFXiWn9DTx0SKmMR7jZhzSSgrkJyWEsshA0rtXexu6NFgZiVpCBpTe1LtJ5dEvV28RlGa/gHVBfNNtL8pWtS8kdl0csK9BPCw958EwhQKFpLs1+Sp3y6NSKuNwZqs2vZqqSs5n1LqnF7PKblQLdOg4Aqx8hNI61FGlhxt+iS0fbFCBvqbIBN6QPNHMPNHMTw+NJZlCRmlU1f8UBWOfS5NlZY/9cKmNVFieTE/Aaf41CSVdXp/r3tN4nfAQW0=
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
