---
- name: install required kubespray deps
  become: yes
  yum:
    pkg: "{{ item }}"
    state: present
  with_items:
    - python-netaddr

# jinja
- include: jinja.yml

# pip
- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade

# Python
- include: python.yml

# PyCharm CE
- include: pycharm.yml
